name: fluttervision
description: fluttervision
version: 1.1.0

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.0.9
  camera: ^0.9.4+14
  google_ml_kit: ^0.12.0
  hooks_riverpod: ^1.0.4
  tflite_flutter: ^0.9.0
  tflite_flutter_helper: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/model.tflite
    - assets/labels.txt

