name: fluttervision
description: fluttervision.
version: 0.9.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.8.1+4
  path_provider: ^2.0.2
  google_ml_kit: ^0.7.0

  tflite_flutter: ^0.9.0
  tflite_flutter_helper: ^0.2.1
  native_device_orientation: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0

flutter_native_splash:
  # flutter pub run flutter_native_splash:create
  color: "000000"
  image: "lib/assets/splash.png"

flutter:
  uses-material-design: true
  assets:
    - assets/model.tflite
